namespace: andreygubarev
name: routeros
version: 0.1.0

readme: README.md

authors:
- Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)

description: Collection for idempotent management of MikroTik RouterOS devices, including upsert of configs.
license_file: LICENSE

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: []

# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies: {}

repository: https://github.com/andreygubarev/ansible-routeros
documentation: https://github.com/andreygubarev/ansible-routeros
homepage: https://github.com/andreygubarev/ansible-routeros
issues: https://github.com/andreygubarev/ansible-routeros/issues

build_ignore: []
