namespace: andreygubarev
name: routeros
version: 0.1.1

readme: README.md

authors:
- Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)

description: Collection for idempotent management of MikroTik RouterOS devices, including upsert of configs.
license_file: LICENSE

tags:
  - routeros
  - mikrotik
  - networking

dependencies:
  - name: community.routeros
    version: 2.6.0

repository: https://github.com/andreygubarev/ansible-routeros
documentation: https://github.com/andreygubarev/ansible-routeros
homepage: https://github.com/andreygubarev/ansible-routeros
issues: https://github.com/andreygubarev/ansible-routeros/issues

build_ignore: []
